encyclopedia/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView

app_name = "encyclopedia"  # Zorg dat dit bovenaan staat om een namespace te registreren

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.page, name="page"),  # Zorg dat deze URL correct overeenkomt met de reverse functie in je view
    path("searchresults/<str:title>", views.searchresults, name="searchresults"),
    path("create", views.create, name="create"),
    path("edit/<str:title>", views.edit, name="edit"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from random import choice
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from . import util
from markdown2 import Markdown
markdowner = Markdown()


class NewEntryForm(forms.Form):
    entry = forms.CharField(label="Search", widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))

class CreateForm(forms.Form):
    title = forms.CharField(label="New Title", widget=forms.TextInput(attrs={'placeholder': 'Name Page'}))
    body = forms.CharField(label="New Body", widget=forms.Textarea(attrs={'placeholder': 'text space' , 'rows': 3}))

class EditForm(forms.Form):
    title = forms.CharField(label="Edit Title", widget=forms.TextInput(attrs={'placeholder': 'Name Page'}))
    body = forms.CharField(label="Edit Body", widget=forms.Textarea(attrs={'placeholder': 'text space' , 'rows': 3}))



def index(request):
    if request.method == "POST":  # melding van een POST -> activeer
        form = NewEntryForm(request.POST)  # sla melding POST op
        if form.is_valid():  # valide? -> Ga door
            GoToEntry = form.cleaned_data["entry"]  # clean data
            
            if util.get_entry(GoToEntry):  # -> bestaat entry? ga door!
                
                #ga naar pagina encyclopedia:page + parameter title
                return HttpResponseRedirect(reverse("encyclopedia:page", args=[GoToEntry])) 
            
            else:
                # Entry bestaat niet, toon een foutmelding op de searchresults pagina
                return HttpResponseRedirect(reverse("encyclopedia:searchresults", args=[GoToEntry]))
                

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": NewEntryForm()
    })

def page(request, title):

    
    content = markdowner.convert(util.get_entry(title)) #handmatig content uit entriess halen ahv title
    if content is None:
        return render(request, "encyclopedia/searchresults.html", {
            "message": f"The entry '{title}' was not found."
        })

    return render(request, "encyclopedia/page.html", {
        "title": title,
        "content": content,
        "entries": util.list_entries(),
        "form": NewEntryForm()
    })

def searchresults(request, title):
    options = []
    for entry in util.list_entries():
        if title.lower() in entry.lower():
            options.append(entry)

    return render(request, "encyclopedia/searchresults.html", {
        "message": f"The entry '{title}' was not found. Did you mean:",
        "entries": util.list_entries(),
        "form": NewEntryForm(),
        "options": options,
    })

def create(request):
    if request.method == "POST":  # melding van een POST -> activeer
        form = CreateForm(request.POST)  # sla melding POST op
        if form.is_valid():  # valide? -> Ga door
            PageTitle = form.cleaned_data["title"]  # clean data
            PageContent = form.cleaned_data["body"]  # clean data
            if util.get_entry(PageTitle):  # -> bestaat title al? Stop dan!
                return render(request, "encyclopedia/create.html", { 
                    "form_page": form,
                    "error_message": "Already in use",
                })
            else:
                util.save_entry(PageTitle, PageContent)
                return HttpResponseRedirect(reverse("encyclopedia:index")) 
    return render(request, "encyclopedia/create.html", {
        "form_page": CreateForm(),        
        "form": NewEntryForm(),
    })

def edit(request, title):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            PageTitle = form.cleaned_data["title"]
            PageContent = form.cleaned_data["body"]
            util.save_entry(PageTitle, PageContent)
            return HttpResponseRedirect(reverse("encyclopedia:index")) 
        
    content = util.get_entry(title) #handmatig content uit entriess halen ahv title
    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "content": content,
        "edit_form": EditForm(initial={'title':title, "body":content}),
        "form": NewEntryForm(),
    })

def random(request):
    listentries = util.list_entries()
    randomentry = choice(listentries)
    return HttpResponseRedirect(reverse("encyclopedia:page", args=[randomentry])) 

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create page</h1>

    {% if error_message %}
    <div style="color: red;">
        <strong>{{ error_message }}</strong>
    </div>
    {% endif %}

    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {{ form_page }}
        <input type="submit" value="Submit">
    </form>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
    

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}


    {% if title %}
        <h1>Edit: {{title}}</h1>
    {% endif %}

    {% if title %}
    {% if content %}
    <div>
        <form action="{% url 'encyclopedia:edit' title %}" method="post">
            {% csrf_token %}
            {{ edit_form }}
            <input type="submit" value="Submit">
        </form>
    </div>
    {% endif %}
            <a href="{% url 'encyclopedia:page' title %}"> Edit </a>
    {% endif %}



{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
    {% if error_message %}
    <div style="color: red;">
        <strong>{{ error_message }}</strong>
    </div>
    {% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">
                        <button class="greenbutton">
                            Random Page
                        </button>
                    </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}


    {% if title %}
        <h1>{{title}}</h1>
    {% endif %}

    {% if content %}
    <div>
        {{content|safe}}
    </div>
    {% endif %}

    {% if title %}
            <a href="{% url 'encyclopedia:edit' title %}"> Edit </a>
            
    {% endif %}



{% endblock %}

encyclopedia/templates/encyclopedia/searchresults.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    {% if message %}
    <div style="color: red;">
        <strong>{{ message }}</strong>
    </div>
    {% endif %}
    <br>

    <ul>
        {% for option in options %}
            <li><a href="{% url 'encyclopedia:page' option %}">{{ option }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}